name = "Dramaturg"
uuid = "f5e8a5c5-9f0a-4b0a-8e0a-5f5e5f5e5f5e"
version = "0.1.0"
authors = ["C. W. Blackwell"]

[deps]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
Test = "1.11.0"
julia = "1.6"
