using Dramaturg

#=

A quick test. Prints to stdout triplets of human-readable descriptions based ona triplet of:

	surface-form, lemma, pos-tag

Usage:

	julia --project=. examples/pos_descreiptions.jl > check-pos-descriptions.md

=#

# Your three examples

println("# Your examples")
println(describe_pos("lu/setai", "lu/w", "v3sfim---"; markdown=false))
println(describe_pos("ai)/tia", "ai)/tios", "a-s---fnp"))
println(describe_pos("ai)/tia", "ai)ti/a", "n-s---fa-"))
println(describe_pos("de/", "de/", "c--------"))
println(describe_pos("oi)moi/", "oi)moi/", "i--------"))
println(describe_pos("kalo/teron", "kalw=s", "d-------c"))
println(describe_pos("kalote/rou", "kalo/s", "a-s---ngc"))

println("Larger Set\n--------------------")
println(describe_pos("a)/nqrwpos", "a)/nqrwpos", "n-s---mn-"))
println()
println()
println(describe_pos("a)nqrw/pou", "a)/nqrwpos", "n-s---mg-"))
println()
println()
println(describe_pos("a)/nqrwpoi", "a)/nqrwpos", "n-p---mn-"))
println()
println()
println(describe_pos("a)/nqrwpoi", "a)/nqrwpos", "n-p---mv-"))
println()
println()
println(describe_pos("krh/nh", "krh/nh", "n-s---fn-"))
println()
println()
println(describe_pos("krh/nh", "krh/nh", "n-s---fv-"))
println()
println()
println(describe_pos("krh/nhn", "krh/nh", "n-s---fa-"))
println()
println()
println(describe_pos("e)/lusa", "e)lu/w", "v1saia---"))
println()
println()
println(describe_pos("e)/lusa", "e)/lu", "v1saia---"))
println()
println()
println(describe_pos("e)/lusa", "lu/w", "v1saia---"))
println()
println()
println(describe_pos("lu=e", "lu/w", "v2spma---"))
println()
println()
println(describe_pos("lu=e", "lu/w", "v3s-ia---"))
println()
println()
println(describe_pos("e)luo/meqa", "e)lu/w", "v1ppie---"))
println()
println()
println(describe_pos("e)luo/meqa", "e)lu/w", "v1p-ie---"))
println()
println()
println(describe_pos("e)luo/meqa", "lu/w", "v1p-ie---"))
println()
println()
println(describe_pos("e)luo/meqa", "e)lu", "v1p-ie---"))
println()
println()
println(describe_pos("e)luo/meqa", "lu/w", "v1p-ie---"))
println()
println()
println(describe_pos("lu/w", "lu/w", "v1spsa---"))
println()
println()
println(describe_pos("lu/w", "lu/w", "v1spia---"))
println()
println()
println(describe_pos("lu/w", "lu", "v1spsa---"))
println()
println()
println(describe_pos("lu/w", "lu/w", "v1spsa---"))
println()
println()
println(describe_pos("lu/w", "lu", "v1spia---"))
println()
println()
println(describe_pos("lu/w", "lu/w", "v1spia---"))
println()
println()
println(describe_pos("poiw=n", "po/a", "n-p---fg-"))
println()
println()
println(describe_pos("poiw=n", "poie/w", "v-sppamn-"))
println()
println()
println(describe_pos("poiw=n", "poio/s", "a-p---fg-"))
println()
println()
println(describe_pos("poiw=n", "poio/s", "a-p---mg-"))
println()
println()
println(describe_pos("poiw=n", "poio/s", "a-p---ng-"))
println()
println()
println(describe_pos("poiw=n", "poio/w", "v-sppamv-"))
println()
println()
println(describe_pos("poiw=n", "poio/w", "v-sppann-"))
println()
println()
println(describe_pos("poiw=n", "poio/w", "v-sppanv-"))
println()
println()
println(describe_pos("poiw=n", "poio/w", "v-sppana-"))
println()
println()
println(describe_pos("poiw=n", "poio/w", "v-sppamn-"))
println()
println()
println(describe_pos("poiw=n", "poio/w", "v--pna---"))
println()
println()
println(describe_pos("poiou=ntos", "poie/w", "v-sppamg-"))
println()
println()
println(describe_pos("poiou=ntos", "poie/w", "v-sppang-"))
println()
println()
println(describe_pos("poiou=ntos", "poio/w", "v-sppamg-"))
println()
println()
println(describe_pos("poiou=ntos", "poio/w", "v-sppang-"))
println()
println()
println(describe_pos("luqh/sesqe", "lu/w", "v2pfip---"))
println()
println()
println(describe_pos("eu)=", "eu)=", "d--------"))
println()
println()
println(describe_pos("o(/s", "o(/s", "p-s---mn-"))
println()
println()
println(describe_pos("kalw=s", "kalo/s", "x--------"))
println()
println()
println(describe_pos("sofwte/ran", "sofwte/ra", "a-s---fa-"))
println()
println()
println(describe_pos("sofwte/ran", "sofo/s", "a-s---fa-"))
println()
println()
println(describe_pos("sofwta/tou", "sofo/s", "a-s---mgs"))
println()
println()
println(describe_pos("sofwta/tou", "sofo/s", "a-s---ngs"))
println()
println()
println(describe_pos("e)bla/bhn", "bla/ptw", "v3paip---"))
println()
println()
println(describe_pos("e)bla/bhn", "bla/ptw", "v1saip---"))
println()
println()
println(describe_pos("parainou/meqa", "paraine/w", "v1ppie---"))
println()
println()
println(describe_pos("parainou/meqa", "paraine/w", "v1ppie---"))
println()
println()
println(describe_pos("parainou/meqa", "paraine/w", "v1p-ie---"))
println()
println()
println(describe_pos("parainou/meqa", "paraine/w", "v1p-ie---"))
println()
println()
println(describe_pos("parainei=te", "paraine/w", "v2ppma---"))
println()
println()
println(describe_pos("parainei=te", "paraine/w", "v2ppoa---"))
println()
println()
println(describe_pos("parainei=te", "paraine/w", "v2ppia---"))
println()
println()
println(describe_pos("parainei=te", "paraine/w", "v2ppma---"))
println()
println()
println(describe_pos("parainei=te", "paraine/w", "v2ppoa---"))
println()
println()
println(describe_pos("parainei=te", "paraine/w", "v2ppia---"))
println()
println()
println(describe_pos("dei=", "de/omai", "v2spie---"))
println()
println()
println(describe_pos("dei=", "de/w1", "v2spie---"))
println()
println()
println(describe_pos("dei=", "de/w1", "v2spma---"))
println()
println()
println(describe_pos("dei=", "de/w1", "v3spia---"))
println()
println()
println(describe_pos("dei=", "de/w1", "v3s-ia---"))
println()
println()
println(describe_pos("dei=", "de/w2", "v2spie---"))
println()
println()
println(describe_pos("dei=", "de/w2", "v2spma---"))
println()
println()
println(describe_pos("dei=", "de/w2", "v3spia---"))
println()
println()
println(describe_pos("dei=", "de/w2", "v3s-ia---"))
println()
println()
println(describe_pos("dei=", "dei=", "v3s-ia---"))
println()
println()
println(describe_pos("deo/ntwn", "de/on", "n-p---ng-"))
println()
println()
println(describe_pos("deo/ntwn", "de/w1", "v3ppma---"))
println()
println()
println(describe_pos("deo/ntwn", "de/w1", "v-pppamg-"))
println()
println()
println(describe_pos("deo/ntwn", "de/w1", "v-pppang-"))
println()
println()
println(describe_pos("deo/ntwn", "de/w1", "v3ppma---"))
println()
println()
println(describe_pos("deo/ntwn", "de/w1", "v-pppamg-"))
println()
println()
println(describe_pos("deo/ntwn", "de/w1", "v-pppang-"))
println()
println()
println(describe_pos("deo/ntwn", "de/w2", "v-pppamg-"))
println()
println()
println(describe_pos("deo/ntwn", "de/w2", "v-pppang-"))
println()
println()
println(describe_pos("deo/ntwn", "de/w2", "v3ppma---"))
println()
println()
println(describe_pos("deo/ntwn", "dei=", "v-pppamg-"))
println()
println()
println(describe_pos("deo/ntwn", "dei=", "v-pppang-"))
println()
println()
println(describe_pos("deo/ntwn", "dei=", "v3ppma---"))
println()
println()
println(describe_pos("dh/sw", "de/omai", "v2saie---"))
println()
println()
println(describe_pos("dh/sw", "de/w1", "v1sasa---"))
println()
println()
println(describe_pos("dh/sw", "de/w1", "v1sfia---"))
println()
println()
println(describe_pos("dh/sw", "de/w1", "v2saim---"))
println()
println()
println(describe_pos("dh/sw", "de/w2", "v1sasa---"))
println()
println()
println(describe_pos("dh/sw", "de/w2", "v2saim---"))
println()
println()
println(describe_pos("dh=sa", "de/w1", "v1saia---"))
println()
println()
println(describe_pos("dh=sa", "de/w2", "v1saia---"))
println()
println()
println(describe_pos("deou=mai", "de/w2", "v1sfim---"))
println()
println()
println(describe_pos("de/w", "de/w1", "v1spsa---"))
println()
println()
println(describe_pos("de/w", "de/w1", "v1spia---"))
println()
println()
println(describe_pos("de/w", "de/w2", "v1spsa---"))
println()
println()
println(describe_pos("de/w", "de/w2", "v1spia---"))
println()
println()
println(describe_pos("de/w", "dei=", "v1spsa---"))
println()
println()
println(describe_pos("de/w", "dei=", "v1spia---"))
println()
println()
println(describe_pos("dh/w", "dh/w", "v1spsa---"))
println()
println()
println(describe_pos("dh/w", "dh/w", "v1spia---"))
println()
println()
println(describe_pos("dh/w", "dh=os", "a-d---mn-"))
println()
println()
println(describe_pos("dh/w", "dh=os", "a-d---mv-"))
println()
println()
println(describe_pos("dh/w", "dh=os", "a-d---ma-"))
println()
println()
println(describe_pos("dh/w", "dh=os", "a-d---nn-"))
println()
println()
println(describe_pos("dh/w", "dh=os", "a-d---nv-"))
println()
println()
println(describe_pos("dh/w", "dh=os", "a-d---na-"))
println()
println()
println(describe_pos("dh/w", "dh=os", "a-s---mg-"))
println()
println()
println(describe_pos("dh/w", "dh=os", "a-s---ng-"))
println()
println()
println(describe_pos("ei)", "ei)", "c--------"))
println()
println()
println(describe_pos("ei)=", "ei)", "c--------"))
println()
println()
println(describe_pos("ei)=", "ei)=mi", "v2spia---"))
println()
println()
println(describe_pos("ei)=", "ei)mi/", "v2spia---"))
println()
println("--------------------------------")
println("--- done -----------------------")
println()