# Configuration for Dramaturg — CEX loading, tokenization, and elision indexing

[input]
cex_path = "source-data/texts/frogs-speech-speaker.cex"
text_urn = "urn:cts:greekLit:tlg0019.tlg009.fu.sp:" 
file_name = "Aristophanes_Frogs"
filter_paratext = "speaker" # filter out passages with this string in the URN.

#cex_path = "source-data/texts/demeter.cex"  
#text_urn = "urn:cts:greekLit:tlg0013.tlg002.fucex:"  
#file_name = "Homeric_Hymn_to_Demeter"
#filter_paratext = "" # filter out passages with this string in the URN.

#cex_path = "source-data/texts/herodotus.cex"
#text_urn = "urn:cts:greekLit:tlg0016.tlg001.grc:"
#file_name = "Herodotus"
#filter_paratext = "" # filter out passages with this string in the URN.


[output]
html_lines_per_page = 25
html_output_dir = "html/pages"
html_template_dir = "../templates"
html_index_template = "index.html"
html_page_template = "reader_page.html"

[lexicon]
lsj_cex = "https://github.com/Eumaeus/cite_lsj_cex/raw/main/lsj_chicago.cex"

[morphology]
pos_data = "path/to/morpheus_output.tsv"

# NEW sections for this milestone
[processing]
data_root = "data"                       # base folder for all generated files
tokenized_dir = "tokenized"
indexes_dir = "indexes"
vocabulary_dir = "vocabulary"
tokenized_suffix = "_tokenized.cex"
elided_index_suffix = "_elided.tsv"
elided_histogram_suffix = "_elided_histogram.tsv"
word_histogram_suffix = "_word_histogram.tsv"
vocabulary_unicode_suffix = "_uc_vocabulary.txt"
vocabulary_beta_suffix = "_beta_vocabulary.txt"


[editorial]
elision_dict      = "source-data/dictionaries/editorial_dict_elision.tsv"
enclitics_dict    = "source-data/dictionaries/editorial-dict-enclitics.tsv"
anastrophe_dict   = "source-data/dictionaries/editorial_dict_anastrophe.tsv"
lsj_index 			= "source-data/dictionaries/lsj_index.tsv"
lsj_index_beta		= "source-data/dictionaries/lsj_index_beta.tsv"

