# scripts/initial_cex.jl
# Creates text-specific morphology
# (updated to also incorporate user-generated morphology TSV files from config["editorial"]["user_morphology_dir"])

using Dates
using BetaReader          # required for beta_to_unicode inside morphology.jl
include("../src/morphology.jl")
include("../src/config.jl")

config = read_config()
println("Loaded config for text: ", config["input"]["text_urn"])

TSV_PATH = config["morphology"]["morph_lemmata_alignment"]
CEX_PATH = config["morphology"]["local_morph_dict"]

# Generate a date-time base for unique object IDs (your preferred style)
base_time = Dates.format(Dates.now(Dates.UTC), "yyyymmddTHHMMSS")
println("Using $CEX_PATH.")
println("Populating dictionary using base timestamp: $base_time.")

# Initialized a set of keys to ensure uniqness
existing_keys = Set{Tuple{String,String,String,String}}()



# ── Load alignment TSV (generated by align_lemmata.jl) ─────────────────────
alignment_lines = readlines(TSV_PATH)

# ── NEW: Load and validate any user-generated morphology TSV files ───────
user_tsv_lines = String[]
user_dir = config["editorial"]["user_morphology_dir"]
line_counter = 0
if isdir(user_dir)
    for file in readdir(user_dir)
        if endswith(lowercase(file), ".tsv")
            println("Working user-morphology file: $file.")
            fullpath = joinpath(user_dir, file)
            lines = readlines(fullpath)
            valid_count = 0
            for (lidx, line) in enumerate(lines)
                stripped = strip(line)
                isempty(stripped) && continue
                fields = split(stripped, '\t')
                if length(fields) != 6
                    println("⚠️  ERROR in user morphology file $fullpath (line $lidx): expected exactly 6 tab-separated fields, found $(length(fields)). Skipping: '$stripped'")
                    continue
                end

                # Check for uniqness
                uc_form  = strip(fields[1])
                uc_lemma = strip(fields[3])
                lsj      = strip(fields[5])
                pos      = strip(fields[6])
                key = (uc_form, uc_lemma, lsj, pos)
                key in existing_keys && continue   # already present → skip
                push!(existing_keys, key)   # so we don't add it again

                push!(user_tsv_lines, stripped)
                valid_count += 1
            end
            println("✅ Loaded $valid_count valid user-generated morphological forms from: $fullpath")
        end
    end
end

# ── Combine alignment + user-generated (user entries are validated) ───────
tsv_lines = vcat(alignment_lines, user_tsv_lines)

# ── Process every line (exactly as before) ───────────────────────────────
new_entries = String[]

for (idx, line) in enumerate(tsv_lines)
    isempty(strip(line)) && continue
    fields = split(line, '\t')
    length(fields) != 6 && continue

    uc_form   = strip(fields[1]) |> String
    bc_form   = strip(fields[2]) |> String
    uc_lemma  = strip(fields[3]) |> String
    bc_lemma  = strip(fields[4]) |> String
    lsj       = strip(fields[5]) |> String
    pos       = strip(fields[6]) |> String

    isempty(uc_form) && continue

    key = (uc_form, uc_lemma, lsj, pos)
    key in existing_keys && continue   # already present → skip
    push!(existing_keys, key)   # so we don't add it again

    # Use your exact describe_pos (markdown = true) and append LSJ link
    desc_base = describe_pos(bc_form, bc_lemma, pos, markdown=true)
    desc      = desc_base * ". See `$lsj`."

    # Unique CITE2-URN object identifier (date-time + 4-digit sequence)
    object_id = base_time * lpad(string(idx), 4, '0')
    full_urn  = "urn:cite2:fufolio:greekmorph.2026a:" * object_id

    # Build the exact # -separated data line required by the .cex
    data_line = join([full_urn, desc, uc_form, bc_form, uc_lemma, bc_lemma, lsj, pos], "#")
    push!(new_entries, data_line)
end

# Append to the CEX file (header + #!citedata line already exist)
#=
open(CEX_PATH, "a") do io
    for entry in new_entries
        println(io, entry)
    end
end
=#

# Overwrite the CEX file (header + #!citedata line already exist)
open(CEX_PATH, "w") do io
    for entry in new_entries
        println(io, entry)
    end
end

println("Added $(length(new_entries)) morphological forms to $CEX_PATH")
